# Generated by Django 2.1.2 on 2018-12-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
                ('permissionname', models.CharField(max_length=30)),
                ('permissionicon', models.CharField(max_length=30)),
                ('flag', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'system_menus',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('flag', models.CharField(choices=[('a', 'admin'), ('n', 'normal')], max_length=1)),
                ('startdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'system_users',
            },
        ),
    ]
